language: cpp
before_script:
- echo "Run before_script"
- sudo apt update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
    provider: script
    skip_cleanup: true
    script:
    - echo "Deploying build $TRAVIS_BUILD_NUMBER ..."
